### ISSUE TITLE
Stub

### ISSUE THREAD

**Issue by sadikkuzu** [gunesmes/testsozluk#4]
Stub için iki çeviri mevcut. Nasıl tekilleştirelim?

https://github.com/gunesmes/testsozluk/blob/43d933ef8bb13bac968c669a2e21ba53e81c6ffd/terms.json#L146-L149

https://github.com/gunesmes/testsozluk/blob/43d933ef8bb13bac968c669a2e21ba53e81c6ffd/terms.json#L506-L509

**Comment by gunesmes** [comment]
Terimlerin birden fazla anlamı olması durumunda ayrık olarak eklemek daha mantıklı olabilir. Bu örnekte ikinci açıklamayı "stubbing, mocking" olarak güncelledim.
